import streamlit as st
import csv
import ast
from z3 import *

# CONFIGURATION
st.set_page_config(page_title="Macadamia Doctor", page_icon="🌰")
st.title("🌰 Dr. Macadamia")

# LOAD KNOWLEDGE BASE (Z3 Logic)
@st.cache_resource
def load_kb():
    # Initialize Z3 Fixedpoint Engine
    fp = Fixedpoint()
    fp.set(engine='datalog')
    Thing = BitVecSort(32)
    
    # ID Helpers
    str_to_id = {}
    id_to_str = {}
    counter = 1

    def get_id(text):
        nonlocal counter
        if not text: return None
        clean = text.strip().strip("'").strip('"')
        if clean not in str_to_id:
            val = BitVecVal(counter, Thing)
            str_to_id[clean] = val
            id_to_str[counter] = clean
            counter += 1
        return str_to_id[clean]

    def get_name(val):
        try: return id_to_str.get(val.as_long(), str(val))
        except: return str(val)

    # Define Relations
    has_symptom = Function('has_symptom', Thing, Thing, BoolSort())
    treated_with = Function('treated_with', Thing, Thing, BoolSort())
    
    fp.register_relation(has_symptom)
    fp.register_relation(treated_with)

    # Data Holders
    all_symptoms = set()
    all_diseases = set()
    z3_fact_lines = [] # Store lines for the .z3 file

    # Load Data from CSV
    try:
        with open('macadamia.csv', mode='r', encoding='utf-8-sig') as f:
            reader = csv.DictReader(f)
            for row in reader:
                disease_name = row['name']
                d_id = get_id(disease_name)
                all_diseases.add(disease_name)
                
                # Load Symptoms
                if row.get('symptoms'):
                    try:
                        # Parse string list "['A', 'B']" -> Python List
                        symptom_list = ast.literal_eval(row['symptoms'])
                        for s in symptom_list:
                            s_id = get_id(s)
                            # Add to Z3 Engine
                            fp.fact(has_symptom(d_id, s_id))
                            all_symptoms.add(s)
                            # Add to Text File List (Corrected scope)
                            z3_fact_lines.append(f"(rule (has_symptom {d_id.as_long()} {s_id.as_long()}))")
                    except: pass
                
                # Load Treatments
                if row.get('treatments'):
                    try:
                        treatment_list = ast.literal_eval(row['treatments'])
                        for t in treatment_list:
                            t_id = get_id(t)
                            # Add to Z3 Engine
                            fp.fact(treated_with(t_id, d_id))
                            # Add to Text File List
                            z3_fact_lines.append(f"(rule (treated_with {t_id.as_long()} {d_id.as_long()}))")
                    except: pass
    except FileNotFoundError:
        return None, None, None, None, None, None, None, None, None, None

    # Define Logic Rules
    t, d, s = Consts('t d s', Thing)
    fp.declare_var(t, d, s)
    
    cures_symptom = Function('cures_symptom', Thing, Thing, BoolSort())
    fp.register_relation(cures_symptom)
    fp.rule(cures_symptom(t, s), [treated_with(t, d), has_symptom(d, s)])

    # GENERATE & SAVE Z3 FILE LOCALLY
    z3_content = ["; Macadamia Knowledge Base - Z3 Facts", "; Auto-generated by Streamlit App", ""]
    
    z3_content.append("; --- ID MAPPING ---")
    sorted_ids = sorted(id_to_str.items())
    for idx, name in sorted_ids:
        z3_content.append(f"; {idx} = {name}")
    
    z3_content.append("")
    z3_content.append("; --- FACTS ---")
    # Append all collected fact lines
    z3_content.extend(z3_fact_lines)
    
    final_z3_string = "\n".join(z3_content)
    
    #SAVE TO DISK HERE
    try:
        with open("macadamia_facts.z3", "w", encoding="utf-8") as z3_file:
            z3_file.write(final_z3_string)
        file_saved = True
    except:
        file_saved = False

    return fp, has_symptom, treated_with, cures_symptom, get_id, get_name, sorted(list(all_symptoms)), sorted(list(all_diseases)), Thing, file_saved

# APP LOGIC
fp, has_symptom_rel, treated_with_rel, cures_symptom_rel, get_id, get_name, symptoms, diseases, ThingType, file_saved = load_kb()

if not fp:
    st.error("Error: 'minimal_macadamia.csv' file not found.")
    st.stop()

if file_saved:
    st.toast("'macadamia.z3' saved to project folder!")

# Helper to extract clean text from Z3 results
def parse_results(ans_obj):
    results = set()
    def collect(expr):
        if is_bv_value(expr): results.add(get_name(expr))
        for child in expr.children(): collect(child)
    collect(ans_obj)
    return sorted(list(results))

# USER INTERFACE
tab1, tab2 = st.tabs(["Symptom Checker", "Disease Lookup"])

# TAB 1: SEARCH BY SYMPTOM
with tab1:
    st.header("Diagnose by Symptom")
    selected_symptom = st.selectbox(
        "I see this symptom:",
        symptoms, 
        index=None, 
        placeholder="Select a symptom..."
        )

    if st.button("Diagnose Problem"):
        st.divider()
        s_id = get_id(selected_symptom)
        
        # DIAGNOSIS (What disease has this symptom?)
        d_var = Const('d', ThingType)
        fp.declare_var(d_var)
        diag_result = fp.query(has_symptom_rel(d_var, s_id))
        
        found_disease = False
        if diag_result == sat:
            diseases_found = parse_results(fp.get_answer())
            for d in diseases_found:
                st.error(f"**Potential Cause:** {d}")
                found_disease = True
        else:
            st.warning("Unknown disease.")

        # PRESCRIPTION (What cures this symptom?)
        if found_disease:
            t_var = Const('t', ThingType)
            fp.declare_var(t_var)
            cure_result = fp.query(cures_symptom_rel(t_var, s_id))
            
            if cure_result == sat:
                treatments = parse_results(fp.get_answer())
                if treatments:
                    st.success(f"**Recommended Treatments:** {', '.join(treatments)}")
                else:
                    st.info("No specific chemical treatment listed.")
            else:
                st.info("No cure found in database.")

# TAB 2: SEARCH BY DISEASE
with tab2:
    st.header("Disease Encyclopedia")
    selected_disease = st.selectbox(
        "Select a Disease or Pest:",
        diseases,
        index=None,
        placeholder="Select a disease..."
        )
    
    if st.button("Get Info"):
        st.divider()
        d_id = get_id(selected_disease)
        
        #  SYMPTOMS (Query: has_symptom(SelectedDisease, s))
        s_var = Const('s', ThingType)
        fp.declare_var(s_var)
        sym_result = fp.query(has_symptom_rel(d_id, s_var))
        
        st.subheader("Symptoms")
        if sym_result == sat:
            found_symptoms = parse_results(fp.get_answer())
            for sym in found_symptoms:
                st.markdown(f"- {sym}")
        else:
            st.write("No symptoms recorded.")

        # GET TREATMENTS (Query: treated_with(t, SelectedDisease))
        t_var = Const('t', ThingType)
        fp.declare_var(t_var)
        treat_result = fp.query(treated_with_rel(t_var, d_id))
        
        st.subheader("Treatments")
        if treat_result == sat:
            found_treatments = parse_results(fp.get_answer())
            for treat in found_treatments:
                st.success(f"{treat}")
        else:
            st.warning("No treatments recorded.")